[package]
name = "rocket-app"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
rocket = "*"
rocket_contrib = "*"
rocket_codegen = "*"

serde = "*"
serde_derive = "*"
serde_json = "*"

auto_impl = { version = "*", path = "../auto_impl/auto_impl" }